filename = 'auction_winners.data';
winners = csvread(filename);
select = randi(size(winners,1));
x0 = winners(select,:);
LB = [2,2,2,2,2,2,2,2,2,2];
UB = [9,9,9,9,9,9,9,9,9,9];
options = saoptimset('simulannealbnd');
options.Display = 'final';
options.PlotFcns = {@saplotf,@saplotbestf,@saplotx,@saplotbestx};
options.AnnealingFcn = @annealfun;
options.TemperatureFcn = @temperaturefast;
options.AcceptanceFcn = @acceptancesa;
options.TolFun = 1.0000e-006;
options.StallIterLimit = 250;
options.MaxFunEvals = 1000;
options.InitialTemperature = 100;
options.ReannealInterval = 50;
options.UsrVar = [];
[x, fval, exitflag, output] = simulannealbnd(@objfun,x0,LB,UB,options);
subplot(2,2,3);
hist(output.myDataX);
title('Selection frequency of nodes');
subplot(2,2,4);
plot(output.myDataT);
title('Temperature');
